[package]
name = "bitwise-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "bitwise"
path = "src/main.rs"

[[bin]]
name = "bitwise-hardening"
path = "src/hardening.rs"

[[bin]]
name = "bitwise-decomp-stress"
path = "src/decomp_stress.rs"

[dependencies]
bitwise-core = { path = "../bitwise-core" }
bitwise-disasm = { path = "../bitwise-disasm" }
bitwise-ir = { path = "../bitwise-ir" }
bitwise-lift = { path = "../bitwise-lift" }
bitwise-decomp = { path = "../bitwise-decomp" }
bitwise-tui = { path = "../bitwise-tui" }
bitwise-debug = { path = "../bitwise-debug" }
bitwise-script = { path = "../bitwise-script" }
bitwise-emu = { path = "../bitwise-emu" }
clap = { version = "4", features = ["derive"] }
colored = "2"
serde_json.workspace = true
thiserror.workspace = true
